defmodule EctoContext.Query do
  @moduledoc """
  Query helpers used by the EEx templates in `priv/templates/ecto_context/`.

  These functions are called at runtime from code generated by `EctoContext`.
  They handle optional query composition — preloading, ordering, limiting,
  selecting, and filtering by association.
  """

  import Ecto.Query

  @doc """
  Filters a query by the foreign key of the given association.

  Resolves the foreign key via `resolve_foreign_key/2`, then applies a `where` clause.
  """
  @spec assoc_where(Ecto.Queryable.t(), module(), atom(), term()) :: Ecto.Query.t()
  def assoc_where(query, module, assoc_atom, parent_id) do
    query_id = resolve_foreign_key(module, assoc_atom)
    where(query, ^[{query_id, parent_id}])
  end

  @doc """
  Resolves the foreign key field for an association.

  Tries Ecto schema reflection first, falls back to `:assoc_id` convention.
  This allows `list_for` to work with both regular `belongs_to` and `static_belongs_to`.
  """
  @spec resolve_foreign_key(module(), atom()) :: atom()
  def resolve_foreign_key(module, assoc_atom) do
    case module.__schema__(:association, assoc_atom) do
      nil -> :"#{assoc_atom}_id"
      assoc -> assoc.owner_key
    end
  end

  @doc "Conditionally preloads associations. No-op when `nil`."
  @spec maybe_preload(Ecto.Queryable.t(), nil | term()) :: Ecto.Query.t()
  def maybe_preload(query, nil), do: query
  def maybe_preload(query, associations), do: preload(query, ^associations)

  @doc "Conditionally applies a 1-arity query function. No-op when `nil`."
  @spec maybe_query(Ecto.Queryable.t(), nil | (Ecto.Queryable.t() -> Ecto.Queryable.t())) ::
          Ecto.Queryable.t()
  def maybe_query(queryable, nil), do: queryable
  def maybe_query(queryable, fun) when is_function(fun, 1), do: fun.(queryable)

  @doc "Conditionally applies an `order_by` clause. No-op when `nil`."
  @spec maybe_order_by(Ecto.Queryable.t(), nil | term()) :: Ecto.Query.t()
  def maybe_order_by(query, nil), do: query
  def maybe_order_by(query, order_by_clauses), do: order_by(query, ^order_by_clauses)

  @doc "Conditionally applies a `select` clause. No-op when `nil`."
  @spec maybe_select(Ecto.Queryable.t(), nil | [atom()]) :: Ecto.Query.t()
  def maybe_select(query, nil), do: query
  def maybe_select(query, fields) when is_list(fields), do: select(query, ^fields)

  @doc "Conditionally applies a `limit` clause. No-op when `nil`."
  @spec maybe_limit(Ecto.Queryable.t(), nil | pos_integer()) :: Ecto.Query.t()
  def maybe_limit(query, nil), do: query
  def maybe_limit(query, limit_num) when is_integer(limit_num), do: limit(query, ^limit_num)
end
